//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaYu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JiaYuEntities : DbContext
    {
        public JiaYuEntities()
            : base("name=JiaYuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<ColorList> ColorList { get; set; }
        public virtual DbSet<DeliveryList> DeliveryList { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Vender> Vender { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Manage> Manage { get; set; }
        public virtual DbSet<ColorRelation> ColorRelation { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Shippings> Shippings { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
