//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaYu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        public string user_id { get; set; }
        public string passwd { get; set; }
        public string email { get; set; }
        public bool verify { get; set; }
        public string m_name { get; set; }
    }
}
